server:
  port: 8085
mybatis:
  type-aliases-package: com.topone.emptest.domain
  mapper-locations: classpath:com/topone/emptest/mapper/*.xml


spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost/hhhh?useLL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
